spring:
  application:
    name: eureka-middle-service-client
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 0
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
