server:
  port: 8181
spring:
  application:
    name: eureka-http-client
management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}

app:
  middle-client:
    name: eureka-middle-service-client
